/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ComponentBackgroundDots: typeof import('./src/components/Login/ComponentBackgroundDots.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Header: typeof import('./src/components/layout/Header/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar/index.vue')['default']
  }
}
