/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Attr: typeof import('./src/components/custome-components/MImage/Attr.vue')['default']
    CanvasAttr: typeof import('./src/components/common/CanvasAttr.vue')['default']
    CommonAttr: typeof import('./src/components/common/CommonAttr.vue')['default']
    CommonEvent: typeof import('./src/components/common/Events/CommonEvent.vue')['default']
    ComponentBackgroundDots: typeof import('./src/components/Login/ComponentBackgroundDots.vue')['default']
    ComponentView: typeof import('./src/components/common/ComponentView/index.vue')['default']
    Editor: typeof import('./src/components/common/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabPanel: typeof import('element-plus/es')['ElTabPanel']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/layout/Header/index.vue')['default']
    Loading: typeof import('./src/components/common/Loading/index.vue')['default']
    Loding: typeof import('./src/components/common/Loding/index.vue')['default']
    MButton: typeof import('./src/components/custome-components/MButton/index.vue')['default']
    MCircle: typeof import('./src/components/custome-components/MCircle/index.vue')['default']
    MImage: typeof import('./src/components/custome-components/MImage/index.vue')['default']
    MRectangle: typeof import('./src/components/custome-components/MRectangle/index.vue')['default']
    MTable: typeof import('./src/components/custome-components/MTable/index.vue')['default']
    MText: typeof import('./src/components/custome-components/MText/index.vue')['default']
    PropsAttr: typeof import('./src/components/common/PropsAttr.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar/index.vue')['default']
    Tab: typeof import('./src/components/layout/Tab/index.vue')['default']
  }
}
